/**
 * Thinkcone Tools catalog metadata and configurations
 * Centre of thinking
 */

export const TOOL_CATEGORIES = [
  { id: 'all', name: 'All Tools' },
  { id: 'organize', name: 'Organize PDF' },
  { id: 'optimize', name: 'Optimize PDF' },
  { id: 'convert-to', name: 'Convert to PDF' },
  { id: 'convert-from', name: 'Convert from PDF' },
  { id: 'image-tools', name: 'Image Converter' },
  { id: 'security', name: 'Edit & Security' },
];

export const TOOLS = [
  {
    id: 'merge',
    name: 'Merge PDF',
    category: 'organize',
    badge: 'Popular',
    icon: 'Layers',
    color: '#005043',
    bgColor: 'rgba(0, 80, 67, 0.1)',
    shortDesc: 'Combine multiple lecture slides, thesis chapters, and assignments into a single document.',
    detailedDesc: 'Select multiple PDF files and combine them into a single unified academic document in seconds.',
    accept: '.pdf',
    multiple: true,
    actionButtonText: 'Merge PDF',
  },
  {
    id: 'split',
    name: 'Split PDF',
    category: 'organize',
    badge: 'Essential',
    icon: 'Scissors',
    color: '#0d7462',
    bgColor: 'rgba(13, 116, 98, 0.1)',
    shortDesc: 'Extract specific pages, question papers, or syllabus units into independent PDF files.',
    detailedDesc: 'Extract individual pages or a range of pages (e.g. 1-3, 5) into separate documents or a ZIP.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Split PDF',
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    category: 'optimize',
    badge: 'Popular',
    icon: 'Minimize2',
    color: '#10b981',
    bgColor: 'rgba(16, 185, 129, 0.1)',
    shortDesc: 'Reduce file size while keeping maximal clarity for seamless portal and LMS uploads.',
    detailedDesc: 'Optimize font structures and object streams to shrink file size with high visual quality.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Compress PDF',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    category: 'convert-from',
    badge: 'High Res',
    icon: 'Image',
    color: '#0284c7',
    bgColor: 'rgba(2, 132, 199, 0.1)',
    shortDesc: 'Extract document diagrams, charts, and presentation pages into high-resolution JPG images.',
    detailedDesc: 'Converts each page of your PDF into crisp, download-ready images or a single ZIP archive.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Convert to JPG',
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    category: 'convert-from',
    badge: 'Lossless',
    icon: 'FileImage',
    color: '#10b981',
    bgColor: 'rgba(16, 185, 129, 0.1)',
    shortDesc: 'Extract document diagrams, charts, and presentation pages into lossless PNG images.',
    detailedDesc: 'Converts each page of your PDF into crisp, transparent-ready PNG images or a single ZIP archive.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Convert to PNG',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    category: 'convert-to',
    badge: 'Essential',
    icon: 'FileImage',
    color: '#7c3aed',
    bgColor: 'rgba(124, 58, 237, 0.1)',
    shortDesc: 'Convert scanned notebook photos, handwritten notes, and receipts into a clean PDF.',
    detailedDesc: 'Combine photos and graphic illustrations into a professional, printable academic PDF document.',
    accept: 'image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp',
    multiple: true,
    actionButtonText: 'Convert to PDF',
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    category: 'organize',
    badge: 'Fast',
    icon: 'RotateCw',
    color: '#d97706',
    bgColor: 'rgba(217, 119, 6, 0.1)',
    shortDesc: 'Fix sideways or upside-down scanned student submissions and lecture pages.',
    detailedDesc: 'Quickly rotate all or selected pages 90° clockwise, 90° counter-clockwise, or 180°.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Rotate PDF',
  },
  {
    id: 'organize',
    name: 'Organize Pages',
    category: 'organize',
    badge: 'Interactive',
    icon: 'Grid',
    color: '#059669',
    bgColor: 'rgba(5, 150, 105, 0.1)',
    shortDesc: 'Sort, reorder, and remove pages in research papers and academic portfolios.',
    detailedDesc: 'Visual page grid allows you to delete unwanted pages and rearrange their sequence.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Save Organized PDF',
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    category: 'convert-from',
    badge: 'Research',
    icon: 'FileText',
    color: '#0f766e',
    bgColor: 'rgba(15, 118, 110, 0.1)',
    shortDesc: 'Extract citations, bibliographies, and text from research articles and books.',
    detailedDesc: 'Fast client-side textual extraction. View directly in-browser, copy, or download as .txt.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Extract Text',
  },
  {
    id: 'watermark',
    name: 'Watermark PDF',
    category: 'security',
    badge: 'Thinkcone Seal',
    icon: 'Stamp',
    color: '#dcbd54',
    bgColor: 'rgba(220, 189, 84, 0.12)',
    shortDesc: 'Stamp Thinkcone Academy copyright or custom confidential watermarks across documents.',
    detailedDesc: 'Protect academic intellectual property with custom diagonal or positioned text stamps.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Apply Watermark',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    category: 'security',
    badge: 'Academic',
    icon: 'Hash',
    color: '#0891b2',
    bgColor: 'rgba(8, 145, 178, 0.1)',
    shortDesc: 'Insert university-compliant page numbers into dissertations and formal project reports.',
    detailedDesc: 'Insert clean page numbers (e.g. "Page 1 of 12" or "1") across headers or footers.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Add Page Numbers',
  },
  {
    id: 'protect',
    name: 'Protect PDF',
    category: 'security',
    badge: 'Security',
    icon: 'Lock',
    color: '#334155',
    bgColor: 'rgba(51, 65, 85, 0.1)',
    shortDesc: 'Lock sensitive grade sheets, certificates, and exam drafts with password encryption.',
    detailedDesc: 'Lock sensitive documents with a custom password and encryption credentials.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Protect PDF',
  },
  {
    id: 'unlock',
    name: 'Unlock PDF',
    category: 'security',
    badge: 'Decrypt',
    icon: 'Unlock',
    color: '#475569',
    bgColor: 'rgba(71, 85, 105, 0.1)',
    shortDesc: 'Remove PDF password restrictions from previously encrypted personal files.',
    detailedDesc: 'Safely decrypt password-protected PDF files for printing and modification.',
    accept: '.pdf',
    multiple: false,
    actionButtonText: 'Unlock PDF',
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    category: 'image-tools',
    badge: 'Fast & Free',
    icon: 'Image',
    color: '#0284c7',
    bgColor: 'rgba(2, 132, 199, 0.1)',
    shortDesc: 'Convert PNG images to JPG format in bulk with custom quality and background fill.',
    detailedDesc: 'Upload multiple PNG images to convert them to optimized JPG files. Download individually or as a single ZIP archive.',
    accept: 'image/png,.png',
    multiple: true,
    actionButtonText: 'Convert to JPG',
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    category: 'image-tools',
    badge: 'Lossless',
    icon: 'FileImage',
    color: '#10b981',
    bgColor: 'rgba(16, 185, 129, 0.1)',
    shortDesc: 'Convert JPG pictures to lossless PNG format with maximum image quality.',
    detailedDesc: 'Upload multiple JPG/JPEG photos to convert them to clean, lossless PNG format in seconds.',
    accept: 'image/jpeg,.jpg,.jpeg',
    multiple: true,
    actionButtonText: 'Convert to PNG',
  },
];
